<?php
/**
 * This is a file automatically generated by the Mouf framework. Do not modify it, as it could be overwritten.
 * This file contains the status of all Mouf global installation processes for packages you have installed.
 * If you are working with a source repository, this file should be commited.
 */
return array (
  0 => 
  array (
    'status' => 'done',
    'type' => 'class',
    'class' => 'Mouf\\Utils\\Constants\\DebugInstaller',
    'package' => 'mouf/utils.constants.debug',
  ),
  1 => 
  array (
    'status' => 'done',
    'type' => 'class',
    'class' => 'Mouf\\Html\\Renderer\\Twig\\MoufTwigEnvironmentInstaller2',
    'package' => 'mouf/html.renderer.twig-extensions',
  ),
  2 => 
  array (
    'status' => 'done',
    'type' => 'class',
    'class' => 'Mouf\\Utils\\Constants\\SecretInstaller',
    'package' => 'mouf/utils.constants.secret',
  ),
  3 => 
  array (
    'status' => 'done',
    'type' => 'class',
    'class' => 'Mouf\\Utils\\Cache\\FileCacheInstaller',
    'package' => 'mouf/utils.cache.file-cache',
  ),
  4 => 
  array (
    'status' => 'done',
    'type' => 'class',
    'class' => 'Mouf\\Utils\\Log\\Psr\\ErrorLogLoggerInstaller',
    'package' => 'mouf/utils.log.psr.errorlog_logger',
  ),
  5 => 
  array (
    'status' => 'done',
    'type' => 'class',
    'class' => 'Mouf\\Utils\\Cache\\ApcCacheInstaller',
    'package' => 'mouf/utils.cache.apc-cache',
  ),
  6 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'src/install.php',
    'package' => 'mouf/html.renderer',
  ),
  7 => 
  array (
    'status' => 'done',
    'type' => 'class',
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibraryManagerInstaller',
    'package' => 'mouf/html.utils.weblibrarymanager',
  ),
  8 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'src/install.php',
    'package' => 'mouf/html.widgets.menu',
  ),
  9 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'src/install.php',
    'package' => 'mouf/utils.session.session-manager',
  ),
  10 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'src/install.php',
    'package' => 'mouf/html.widgets.messageservice',
  ),
  11 => 
  array (
    'status' => 'done',
    'type' => 'class',
    'class' => 'Mouf\\Html\\Template\\BootstrapTemplateInstaller',
    'package' => 'mouf/html.template.bootstrap',
  ),
  12 => 
  array (
    'status' => 'done',
    'type' => 'class',
    'class' => 'Mouf\\Utils\\Common\\Doctrine\\Cache\\CacheInstaller',
    'package' => 'mouf/utils.common.doctrine-cache-wrapper',
  ),
  13 => 
  array (
    'status' => 'done',
    'type' => 'class',
    'class' => 'Mouf\\Utils\\Common\\Doctrine\\Annotations\\AnnotationReaderInstaller',
    'package' => 'mouf/utils.common.doctrine-annotations-wrapper',
  ),
  14 => 
  array (
    'status' => 'done',
    'type' => 'url',
    'url' => 'splash82install/',
    'package' => 'mouf/mvc.splash',
  ),
  15 => 
  array (
    'status' => 'done',
    'type' => 'url',
    'url' => 'splash82install/writeHtAccess',
    'package' => 'mouf/mvc.splash',
  ),
  16 => 
  array (
    'status' => 'done',
    'type' => 'class',
    'class' => 'Mouf\\Console\\ConsoleInstaller',
    'package' => 'mouf/utils.console',
  ),
  17 => 
  array (
    'status' => 'done',
    'type' => 'url',
    'url' => 'dbalconnectioninstall/',
    'package' => 'mouf/database.doctrine-dbal-wrapper',
  ),
  18 => 
  array (
    'status' => 'done',
    'type' => 'url',
    'url' => 'tdbminstall3/',
    'package' => 'mouf/database.tdbm',
  ),
  19 => 
  array (
    'status' => 'done',
    'type' => 'class',
    'class' => 'Mouf\\Utils\\Patcher\\PatchInstaller3',
    'package' => 'mouf/utils.patcher',
  ),
  20 => 
  array (
    'status' => 'done',
    'type' => 'class',
    'class' => 'Mouf\\Database\\Patcher\\DatabasePatchInstaller3',
    'package' => 'mouf/database.patcher',
  ),
  21 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'src/install.php',
    'package' => 'mouf/security.userservice',
  ),
  22 => 
  array (
    'status' => 'done',
    'type' => 'class',
    'class' => 'Mouf\\Security\\UnauthorizedMiddlewareInstaller',
    'package' => 'mouf/security.userservice-splash',
  ),
  23 => 
  array (
    'status' => 'done',
    'type' => 'class',
    'class' => 'Mouf\\Security\\SimpleLoginInstaller',
    'package' => 'mouf/security.simplelogincontroller',
  ),
  24 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'src/install.php',
    'package' => 'mouf/security.rightsservice',
  ),
  25 => 
  array (
    'status' => 'done',
    'type' => 'class',
    'class' => 'Mouf\\Security\\ForbiddenMiddlewareInstaller',
    'package' => 'mouf/security.rightsservice-splash',
  ),
  26 => 
  array (
    'status' => 'done',
    'type' => 'class',
    'class' => 'Mouf\\Security\\DAO\\TablesInstaller',
    'package' => 'mouf/security.daos.tdbm',
  ),
  27 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'install.php',
    'package' => 'mouf/javascript.jquery.jquery',
  ),
  28 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'install.php',
    'package' => 'mouf/javascript.historyjs',
  ),
  29 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'src/install.php',
    'package' => 'mouf/utils.common.formatters',
  ),
  30 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'install.php',
    'package' => 'mouf/html.widgets.evolugrid',
  ),
  31 => 
  array (
    'status' => 'done',
    'type' => 'class',
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Common\\FineInstaller',
    'package' => 'mouf/utils.i18n.fine.common',
  ),
  32 => 
  array (
    'status' => 'done',
    'type' => 'class',
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Translator\\FileTranslatorInstaller',
    'package' => 'mouf/utils.i18n.fine.file-translator',
  ),
  33 => 
  array (
    'status' => 'done',
    'type' => 'class',
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Language\\FineLanguageInstaller',
    'package' => 'mouf/utils.i18n.fine.language-detection',
  ),
  34 => 
  array (
    'status' => 'done',
    'type' => 'class',
    'class' => 'Mouf\\Security\\UserManagement\\UserManagementInstaller',
    'package' => 'mouf/security.user-management-ui',
  ),
  35 => 
  array (
    'status' => 'done',
    'type' => 'url',
    'url' => 'swiftmailserviceinstall/',
    'package' => 'mouf/utils.mailer.swift-mail-service',
  ),
  36 => 
  array (
    'status' => 'done',
    'type' => 'class',
    'class' => 'Mouf\\Security\\Password\\ForgotYourPasswordInstaller',
    'package' => 'mouf/security.forgot-your-password',
  ),
);