<?php
/**
 * This is a file automatically generated by the Mouf framework. Do not modify it, as it could be overwritten.
 */

// Files declared in the extra:mouf:adminRequire section.
require_once __DIR__.'/../vendor/mouf/database.doctrine-dbal-wrapper/src/DBALConnectionAdmin.php';
require_once __DIR__.'/../vendor/mouf/utils.patcher/src/PatchAdmin.php';
require_once __DIR__.'/../vendor/mouf/database.patcher/src/DBPatchAdmin.php';
require_once __DIR__.'/../vendor/mouf/utils.cache.cache-interface/CacheAdmin.php';
require_once __DIR__.'/../vendor/mouf/html.utils.weblibrarymanager/src/WebLibraryAdmin.php';
require_once __DIR__.'/../vendor/mouf/html.widgets.evolugrid/src/EvolugridAdmin.php';
require_once __DIR__.'/../vendor/mouf/database.querywriter/src/QueryWriterAdmin.php';
require_once __DIR__.'/../vendor/mouf/database.tdbm/src/TdbmAdmin.php';
require_once __DIR__.'/../vendor/mouf/mvc.splash-ui/src/SplashUiAdmin.php';
require_once __DIR__.'/../vendor/mouf/utils.cache.psr6-ui/CacheAdmin.php';
require_once __DIR__.'/../vendor/mouf/mvc.splash/src/SplashAdmin.php';
require_once __DIR__.'/../vendor/mouf/mvc.splash/src/Mouf/Mvc/Splash/SplashGenerateService.php';
require_once __DIR__.'/../vendor/mouf/mvc.splash/src/Mouf/Mvc/Splash/Controllers/Admin/SplashPurgeCacheController.php';
require_once __DIR__.'/../vendor/mouf/mvc.splash/src/Mouf/Mvc/Splash/Controllers/Admin/SplashAdminApacheConfigureController.php';
require_once __DIR__.'/../vendor/mouf/mvc.splash/src/Mouf/Mvc/Splash/Controllers/Admin/SplashInstallController.php';
require_once __DIR__.'/../vendor/mouf/utils.mailer.swift-mail-service/src/SwiftMailServiceAdmin.php';
require_once __DIR__.'/../vendor/mouf/utils.i18n.fine.manage.bo/src/ManageBoAdmin.php';

?>