<?php
/**
 * This is a file automatically generated by the Mouf framework. Do not modify it, as it could be overwritten.
 */
use Mouf\MoufManager;
use Interop\Container\ContainerInterface;
MoufManager::initMoufManager();
$moufManager = MoufManager::getMoufManager();

$moufManager->getConfigManager()->setConstantsDefinitionArray(array (
  'DEBUG' => 
  array (
    'defaultValue' => true,
    'type' => 'bool',
    'comment' => 'Set to true to enable debug/development mode.',
    'fetchFromEnv' => true,
  ),
  'SECRET' => 
  array (
    'defaultValue' => 'MtHxYF6LU48XEHugdZqt',
    'type' => 'string',
    'comment' => 'A random string. It should be different for any application deployed.',
    'fetchFromEnv' => true,
  ),
  'DB_HOST' => 
  array (
    'defaultValue' => 'localhost',
    'type' => 'string',
    'comment' => 'The database host (the IP address or URL of the database server).',
    'fetchFromEnv' => true,
  ),
  'DB_PORT' => 
  array (
    'defaultValue' => '',
    'type' => 'int',
    'comment' => 'The database port (the port of the database server, keep empty to use default port).',
    'fetchFromEnv' => true,
  ),
  'DB_NAME' => 
  array (
    'defaultValue' => '',
    'type' => 'string',
    'comment' => 'The name of your database.',
    'fetchFromEnv' => true,
  ),
  'DB_USERNAME' => 
  array (
    'defaultValue' => '',
    'type' => 'string',
    'comment' => 'The username to access the database.',
    'fetchFromEnv' => true,
  ),
  'DB_PASSWORD' => 
  array (
    'defaultValue' => '',
    'type' => 'string',
    'comment' => 'The password to access the database.',
    'fetchFromEnv' => true,
  ),
  'MAIL_HOST' => 
  array (
    'defaultValue' => 'localhost',
    'type' => 'string',
    'comment' => 'The SMTP host to use (the IP address or URL of the database server). For instance, use \'smtp.gmail.com\' to connect to gmail SMTP servers.',
    'fetchFromEnv' => true,
  ),
  'MAIL_PORT' => 
  array (
    'defaultValue' => '25',
    'type' => 'int',
    'comment' => 'The SMTP server port (the port of the SMTP server, keep empty to use default port). For instance, use \'587\' to connect to gmail SMTP servers.',
    'fetchFromEnv' => true,
  ),
  'MAIL_AUTH' => 
  array (
    'defaultValue' => '',
    'type' => 'string',
    'comment' => 'The authentication mechanism for the SMTP server. Can be one of \'\', \'plain\', \'login\', \'crammd5\'. For instance, use \'login\' to connect to gmail SMTP servers.',
    'fetchFromEnv' => true,
  ),
  'MAIL_USERNAME' => 
  array (
    'defaultValue' => '',
    'type' => 'string',
    'comment' => 'The username to connect to the SMTP server. For gmail, use your gmail address.',
    'fetchFromEnv' => true,
  ),
  'MAIL_PASSWORD' => 
  array (
    'defaultValue' => '',
    'type' => 'string',
    'comment' => 'The password to connect to the SMTP server. For gmail, use your gmail password.',
    'fetchFromEnv' => true,
  ),
  'MAIL_SSL' => 
  array (
    'defaultValue' => '',
    'type' => 'string',
    'comment' => 'The SSL mode to use, to connect to the SMTP server, if any. Can be one of \'\', \'ssl\', \'tls\'. For gmail, use \'tls\'.',
    'fetchFromEnv' => true,
  ),
  'MAIL_FROM' => 
  array (
    'defaultValue' => 'ro-reply@localhost',
    'type' => 'string',
    'comment' => 'The \'from\' value used when sending mails.',
    'fetchFromEnv' => true,
  ),
));

$moufManager->setAllVariables(array (
  'splashDefaultControllersNamespace' => 'ShopFunnels\\Controllers\\',
  'splashDefaultViewsDirectory' => 'views/',
));

$moufManager->addComponentInstances(array (
  'Mouf\\Database\\TDBM\\Utils\\MoufDiListener' => 
  array (
    'class' => 'Mouf\\Database\\TDBM\\Utils\\MoufDiListener',
    'external' => false,
    'weak' => false,
  ),
  'Mouf\\Mvc\\Splash\\Controllers\\HttpErrorsController' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Controllers\\HttpErrorsController',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'bootstrapTemplate',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'block.content',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'DEBUG',
        'parametertype' => 'primitive',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'Mouf\\Mvc\\Splash\\Routers\\ExceptionRouter' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Routers\\ExceptionRouter',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'Mouf\\Mvc\\Splash\\Controllers\\HttpErrorsController',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'psr.errorLogLogger',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'Mouf\\Mvc\\Splash\\Routers\\NotFoundRouter' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Routers\\NotFoundRouter',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'Mouf\\Mvc\\Splash\\Controllers\\HttpErrorsController',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'psr.errorLogLogger',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'Mouf\\Mvc\\Splash\\Routers\\PhpVarsCheckRouter' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Routers\\PhpVarsCheckRouter',
    'external' => false,
    'weak' => false,
  ),
  'Mouf\\Mvc\\Splash\\Routers\\SplashDefaultRouter' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Routers\\SplashDefaultRouter',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'return $container;',
        'parametertype' => 'primitive',
        'type' => 'php',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
          0 => 'Mouf\\Mvc\\Splash\\Services\\MoufExplorerUrlProvider',
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'Mouf\\Mvc\\Splash\\Services\\ParameterFetcherRegistry',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 'splashCachePool',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      4 => 
      array (
        'value' => 'psr.errorLogLogger',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      5 => 
      array (
        'value' => 'strict',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      6 => 
      array (
        'value' => 'DEBUG',
        'parametertype' => 'primitive',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
      7 => 
      array (
        'value' => 'return ROOT_URL;',
        'parametertype' => 'primitive',
        'type' => 'php',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setHttp400Handler' => 'Mouf\\Mvc\\Splash\\Controllers\\HttpErrorsController',
    ),
  ),
  'Mouf\\Mvc\\Splash\\Services\\ControllerAnalyzer' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Services\\ControllerAnalyzer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'return $container;',
        'parametertype' => 'primitive',
        'type' => 'php',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'Mouf\\Mvc\\Splash\\Services\\ParameterFetcherRegistry',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'annotationReader',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'Mouf\\Mvc\\Splash\\Services\\ControllerRegistry' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Services\\ControllerRegistry',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'Mouf\\Mvc\\Splash\\Services\\ControllerAnalyzer',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'Mouf\\Mvc\\Splash\\Services\\MoufControllerExplorer',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'Mouf\\Mvc\\Splash\\Services\\MoufControllerExplorer' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Services\\MoufControllerExplorer',
    'external' => false,
    'weak' => false,
  ),
  'Mouf\\Mvc\\Splash\\Services\\MoufExplorerUrlProvider' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Services\\MoufExplorerUrlProvider',
    'external' => false,
    'weak' => false,
  ),
  'Mouf\\Mvc\\Splash\\Services\\ParameterFetcherRegistry' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Services\\ParameterFetcherRegistry',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'Mouf\\Mvc\\Splash\\Services\\SplashRequestFetcher',
          1 => 'Mouf\\Mvc\\Splash\\Services\\SplashRequestParameterFetcher',
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'Mouf\\Mvc\\Splash\\Services\\SplashRequestFetcher' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Services\\SplashRequestFetcher',
    'external' => false,
    'weak' => false,
  ),
  'Mouf\\Mvc\\Splash\\Services\\SplashRequestParameterFetcher' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Services\\SplashRequestParameterFetcher',
    'external' => false,
    'weak' => false,
  ),
  'Mouf\\Mvc\\Splash\\SplashMiddleware' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\SplashMiddleware',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => '__anonymous__bbb3_555180492',
          1 => '__anonymous__bbb3_817177238',
          2 => '__anonymous__bbb3_420569167',
          3 => '__anonymous__bbb3_872310246',
          4 => '__anonymous__bbb3_1202402180',
          5 => '__anonymous__bbb3_1621779688',
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'Mouf\\Security\\DAO\\SecurityRightDao' => 
  array (
    'class' => 'Mouf\\Security\\DAO\\SecurityRightDao',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'tdbmService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'Mouf\\Security\\Rights\\RightsRegistry',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'Mouf\\Security\\DAO\\SecurityUserDao' => 
  array (
    'class' => 'Mouf\\Security\\DAO\\SecurityUserDao',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'tdbmService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'Mouf\\Security\\ForbiddenMiddleware' => 
  array (
    'class' => 'Mouf\\Security\\ForbiddenMiddleware',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'rightsService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => '__anonymous__bbb3_1352213458',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'userService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 'simpleLoginController',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'Mouf\\Security\\Migrations\\CreateUserRoleRightPatch' => 
  array (
    'class' => 'Mouf\\Security\\Migrations\\CreateUserRoleRightPatch',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'patchConnection',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'Mouf\\Security\\Password\\ForgotYourPasswordController' => 
  array (
    'class' => 'Mouf\\Security\\Password\\ForgotYourPasswordController',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'psr.errorLogLogger',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'bootstrapTemplate',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'block.content',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 'twigEnvironment',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      4 => 
      array (
        'value' => 'Mouf\\Security\\Password\\ForgotYourPasswordService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      5 => 
      array (
        'value' => 'userService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      6 => 
      array (
        'value' => 'Mouf\\Security\\Password\\PasswordStrengthCheck',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'Mouf\\Security\\Password\\ForgotYourPasswordService' => 
  array (
    'class' => 'Mouf\\Security\\Password\\ForgotYourPasswordService',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'Mouf\\Security\\DAO\\SecurityUserDao',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'swiftMailer',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'forgotYourPasswordMailTemplate',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 'userService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'Mouf\\Security\\Password\\PasswordStrengthCheck' => 
  array (
    'class' => 'Mouf\\Security\\Password\\PasswordStrengthCheck',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'defaultTranslationService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'Mouf\\Security\\Rights\\RightsRegistry' => 
  array (
    'class' => 'Mouf\\Security\\Rights\\RightsRegistry',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'Mouf\\Security\\UnauthorizedMiddleware' => 
  array (
    'class' => 'Mouf\\Security\\UnauthorizedMiddleware',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'userService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'simpleLoginController',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'Psr7Middlewares\\Middleware\\Payload' => 
  array (
    'class' => 'Psr7Middlewares\\Middleware\\Payload',
    'external' => false,
    'weak' => false,
  ),
  '__anonymous__bbb3_1202402180' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Routers\\Router',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'Mouf\\Mvc\\Splash\\Routers\\SplashDefaultRouter',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous__bbb3_1217305949' => 
  array (
    'class' => 'Mouf\\Utils\\Value\\Variable',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'DEBUG',
        'parametertype' => 'primitive',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous__bbb3_1338679528' => 
  array (
    'class' => 'Mouf\\Utils\\Patcher\\Commands\\ApplyPatchCommand',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'patchService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous__bbb3_1352213458' => 
  array (
    'class' => 'Mouf\\Security\\Controllers\\SimpleForbiddenController',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'bootstrapTemplate',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'block.content',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => '__anonymous__bbb3_1388363450',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous__bbb3_1388363450' => 
  array (
    'class' => 'Mouf\\Security\\Html\\SimpleForbiddenView',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
  ),
  '__anonymous__bbb3_1420332419' => 
  array (
    'class' => 'Mouf\\Utils\\Common\\Condition\\ToCondition',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => '__anonymous__bbb3_1217305949',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous__bbb3_1596919386' => 
  array (
    'class' => 'Doctrine\\DBAL\\Driver\\PDOMySql\\Driver',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
  ),
  '__anonymous__bbb3_1621779688' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Routers\\Router',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'Mouf\\Mvc\\Splash\\Routers\\NotFoundRouter',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous__bbb3_1996553850' => 
  array (
    'class' => 'Mouf\\Utils\\Patcher\\Commands\\ApplyAllPatchesCommand',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'patchService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous__bbb3_2044153617' => 
  array (
    'class' => 'Doctrine\\Common\\EventManager',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
  ),
  '__anonymous__bbb3_409490270' => 
  array (
    'class' => 'Mouf\\Utils\\Patcher\\Commands\\SkipPatchCommand',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'patchService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous__bbb3_420569167' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Routers\\Router',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'Mouf\\Mvc\\Splash\\Routers\\PhpVarsCheckRouter',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous__bbb3_555180492' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Routers\\Router',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'Mouf\\Mvc\\Splash\\Routers\\ExceptionRouter',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous__bbb3_604724816' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Common\\FineTwigExtension',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'defaultTranslationService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous__bbb3_667843363' => 
  array (
    'class' => 'Mouf\\Console\\Command\\MoufRewriteCommand',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'mouf:rewrite',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous__bbb3_767223829' => 
  array (
    'class' => 'Mouf\\Utils\\Patcher\\Commands\\ListPatchesCommand',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'patchService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous__bbb3_817177238' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Routers\\Router',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'return $container->get(\'whoopsMiddleware\');',
        'parametertype' => 'primitive',
        'type' => 'php',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => NULL,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => '__anonymous__bbb3_1420332419',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous__bbb3_828720274' => 
  array (
    'class' => 'Mouf\\Utils\\Patcher\\Commands\\RevertPatchCommand',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'patchService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous__bbb3_872310246' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Routers\\Router',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'return $container->get(\'Psr7Middlewares\\\\Middleware\\\\Payload\');',
        'parametertype' => 'primitive',
        'type' => 'php',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous__bbb3_947822775' => 
  array (
    'class' => 'Mouf\\Utils\\Patcher\\Commands\\ResetPatchesCommand',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'patchService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'annotationReader' => 
  array (
    'weak' => false,
    'comment' => '',
    'class' => 'Doctrine\\Common\\Annotations\\CachedReader',
    'external' => false,
    'code' => '// Using composer autoloader
$loader = require ROOT_PATH . \'vendor/autoload.php\';
\\Doctrine\\Common\\Annotations\\AnnotationRegistry::registerLoader(array($loader, \'loadClass\'));

// Creating a new AnnotationReader
$reader = new \\Doctrine\\Common\\Annotations\\AnnotationReader();
return new \\Doctrine\\Common\\Annotations\\CachedReader($reader, $container->get("defaultDoctrineCache"));',
  ),
  'apcCacheService' => 
  array (
    'class' => 'Mouf\\Utils\\Cache\\ApcCache',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'defaultTimeToLive' => 
      array (
        'value' => 3600,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'prefix' => 
      array (
        'value' => 'SECRET',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
    ),
    'fieldBinds' => 
    array (
      'fallback' => 'fileCacheService',
    ),
  ),
  'block.content' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
  ),
  'block.footer' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
  ),
  'block.header' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
  ),
  'block.left' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
  ),
  'block.right' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
  ),
  'boldFormatter' => 
  array (
    'class' => 'Mouf\\Utils\\Common\\Formatters\\PrefixSuffixFormatter',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => '<b>',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => '</b>',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'bootstrapRenderer' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\FileBasedRenderer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'vendor/mouf/html.template.bootstrap/src/templates',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'rendererCacheService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'template',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 0,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'bootstrapTemplate' => 
  array (
    'class' => 'Mouf\\Html\\Template\\BootstrapTemplate',
    'external' => false,
    'weak' => false,
    'setterBinds' => 
    array (
      'setContent' => 'block.content',
      'setLeft' => 'block.left',
      'setRight' => 'block.right',
      'setHeader' => 'block.header',
      'setFooter' => 'block.footer',
      'setWebLibraryManager' => 'defaultWebLibraryManager',
      'setTemplateRenderer' => 'bootstrapRenderer',
      'setDefaultRenderer' => 'defaultRenderer',
    ),
    'setterProperties' => 
    array (
      'setTitle' => 
      array (
        'value' => 'Shop Funnels',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'cascadingLanguageDetection' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Language\\CascadingLanguageDetection',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'fixedEnglishLanguageDetection',
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'component.bootstrap' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'vendor/components/bootstrap/js/bootstrap.js',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
          0 => 'vendor/components/bootstrap/css/bootstrap.min.css',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'component.jquery' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'vendor/components/jquery/jquery.js',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'console' => 
  array (
    'class' => 'Mouf\\Console\\ConsoleApplication',
    'external' => false,
    'weak' => false,
    'setterBinds' => 
    array (
      'setHelperSet' => 'helperSet',
      'setCommands' => 
      array (
        0 => '__anonymous__bbb3_667843363',
        1 => 'dbalRunSqlCommand',
        2 => 'dbalImportCommand',
        3 => 'dbalReservedWordsCommand',
        4 => 'generateCommand',
        5 => '__anonymous__bbb3_767223829',
        6 => '__anonymous__bbb3_1996553850',
        7 => '__anonymous__bbb3_1338679528',
        8 => '__anonymous__bbb3_409490270',
        9 => '__anonymous__bbb3_828720274',
        10 => '__anonymous__bbb3_947822775',
      ),
    ),
  ),
  'customRenderer' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\FileBasedRenderer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'src/templates',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'rendererCacheService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'custom',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 0,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      4 => 
      array (
        'value' => 'twigEnvironment',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'daoFactory' => 
  array (
    'class' => 'ShopFunnels\\Dao\\Generated\\DaoFactory',
    'external' => false,
    'fieldProperties' => 
    array (
    ),
    'setterProperties' => 
    array (
    ),
    'fieldBinds' => 
    array (
    ),
    'setterBinds' => 
    array (
      'setRoleDao' => 'roleDao',
      'setRoleRightDao' => 'roleRightDao',
      'setUserDao' => 'userDao',
    ),
    'weak' => false,
    'comment' => '',
  ),
  'dbalConnection' => 
  array (
    'class' => 'Doctrine\\DBAL\\Connection',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'return array(
    "host" => DB_HOST,
    "user" => DB_USERNAME,
    "password" => DB_PASSWORD,
    "port" => DB_PORT,
    "dbname" => DB_NAME,
    "charset" => "utf8",
    "driverOptions" => array(
        1002 =>"SET NAMES utf8"
    )
);',
        'parametertype' => 'primitive',
        'type' => 'php',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => '__anonymous__bbb3_1596919386',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'doctrineDbalConfiguration',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => '__anonymous__bbb3_2044153617',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'dbalConnectionHelper' => 
  array (
    'class' => 'Doctrine\\DBAL\\Tools\\Console\\Helper\\ConnectionHelper',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'dbalConnection',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'dbalImportCommand' => 
  array (
    'class' => 'Doctrine\\DBAL\\Tools\\Console\\Command\\ImportCommand',
    'external' => false,
    'weak' => false,
  ),
  'dbalReservedWordsCommand' => 
  array (
    'class' => 'Doctrine\\DBAL\\Tools\\Console\\Command\\ReservedWordsCommand',
    'external' => false,
    'weak' => false,
  ),
  'dbalRunSqlCommand' => 
  array (
    'class' => 'Doctrine\\DBAL\\Tools\\Console\\Command\\RunSqlCommand',
    'external' => false,
    'weak' => false,
  ),
  'defaultDoctrineCache' => 
  array (
    'weak' => false,
    'comment' => '',
    'class' => 'Doctrine\\Common\\Cache\\ArrayCache',
    'external' => false,
    'code' => '// If DEBUG mode is on, let\'s just use an ArrayCache.
if (DEBUG) {
	$driver = new \\Doctrine\\Common\\Cache\\ArrayCache();
} else {
	// If APC is available, let\'s use APC
	if (extension_loaded("apcu")) {
		$driver = new \\Doctrine\\Common\\Cache\\ApcuCache();
	} else if (extension_loaded("apc")) {
		$driver = new \\Doctrine\\Common\\Cache\\ApcCache();
	} else {
		$driver = new \\Doctrine\\Common\\Cache\\PhpFileCache(sys_get_temp_dir().\'/doctrinecache\');
	}
}
$driver->setNamespace(SECRET);
return $driver;
',
  ),
  'defaultRenderer' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\AutoChainRenderer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'rendererCacheService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'defaultTranslationService' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Common\\FineCascadingTranslator',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'fileTranslatorService',
          1 => 'forgotYourPasswordTranslator',
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'defaultWebLibraryManager' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibraryManager',
    'external' => false,
    'weak' => false,
    'setterBinds' => 
    array (
      'setWebLibraries' => 
      array (
        0 => 'rootUrlInlineWebLibrary',
        1 => 'shopFunnelsLibraryManager',
        2 => 'messageServiceLibrary',
      ),
    ),
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'defaultRenderer',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterProperties' => 
    array (
    ),
  ),
  'doctrineDbalConfiguration' => 
  array (
    'class' => 'Doctrine\\DBAL\\Configuration',
    'external' => false,
    'weak' => false,
    'setterProperties' => 
    array (
      'setFilterSchemaAssetsExpression' => 
      array (
        'value' => '/^(?!patches$).*/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'doctrineMoufCache' => 
  array (
    'class' => 'Mouf\\Utils\\Common\\Doctrine\\Cache\\DoctrineCacheAdapter',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'defaultDoctrineCache',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'evolugridLibrary' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/html.widgets.evolugrid/js/evolugrid.js',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setDependencies' => 
      array (
        0 => 'jQueryLibrary',
      ),
    ),
  ),
  'fileCacheService' => 
  array (
    'class' => 'Mouf\\Utils\\Cache\\FileCache',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'defaultTimeToLive' => 
      array (
        'value' => 3600,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'prefix' => 
      array (
        'value' => 'SECRET',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'fileTranslatorService' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Translator\\FileTranslator',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'resources/',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'cascadingLanguageDetection',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'fixedEnglishLanguageDetection' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Language\\FixedLanguageDetection',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'en',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'forgotYourPasswordMailTemplate' => 
  array (
    'class' => 'TheCodingMachine\\Mail\\Template\\SwiftTwigMailTemplate',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'twigEnvironment',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'vendor/mouf/security.forgot-your-password/src/templates/forgotyourpasswordmail.twig',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterProperties' => 
    array (
      'setFromAddresses' => 
      array (
        'value' => 'MAIL_FROM',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'forgotYourPasswordTranslator' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Translator\\FileTranslator',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'vendor/mouf/security.forgot-your-password/ressources/',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'cascadingLanguageDetection',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'generateCommand' => 
  array (
    'class' => 'TheCodingMachine\\TDBM\\Commands\\GenerateCommand',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'tdbmConfiguration',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'helperSet' => 
  array (
    'class' => 'Mouf\\Console\\HelperSet',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          'db' => 'dbalConnectionHelper',
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'italicFormatter' => 
  array (
    'class' => 'Mouf\\Utils\\Common\\Formatters\\PrefixSuffixFormatter',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => '<i>',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => '</i>',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'jQueryHistory' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/javascript.historyjs/scripts/bundled/html4+html5/jquery.history.js',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'jQueryLibrary' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/javascript.jquery.jquery/jquery-1.11.0.min.js',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'messageServiceLibrary' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/html.widgets.messageservice/messages.css',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'messageWidget' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\MessageService\\Widget\\MessageWidget',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'messageProvider' => 'userMessageService',
    ),
  ),
  'moufTwigExtension' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\Twig\\MoufTwigExtension',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'return $container;',
        'parametertype' => 'primitive',
        'type' => 'php',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'namingStrategy' => 
  array (
    'class' => 'TheCodingMachine\\TDBM\\Utils\\DefaultNamingStrategy',
    'external' => false,
    'weak' => false,
  ),
  'packageRenderer_mouf/html.utils.weblibrarymanager' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\FileBasedRenderer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'vendor/mouf/html.utils.weblibrarymanager/src/templates',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'rendererCacheService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'package',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 0,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      4 => 
      array (
        'value' => 'twigEnvironment',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'packageRenderer_mouf/html.widgets.menu' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\FileBasedRenderer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'vendor/mouf/html.widgets.menu/src/templates',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'rendererCacheService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'package',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 0,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      4 => 
      array (
        'value' => 'twigEnvironment',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'packageRenderer_mouf/html.widgets.messageservice' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\FileBasedRenderer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'vendor/mouf/html.widgets.messageservice/src/templates',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'rendererCacheService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'package',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 0,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      4 => 
      array (
        'value' => 'twigEnvironment',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'packageRenderer_mouf/security.forgot-your-password' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\FileBasedRenderer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'vendor/mouf/security.forgot-your-password/src/templates',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'rendererCacheService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'package',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 0,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      4 => 
      array (
        'value' => 'twigEnvironment',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'packageRenderer_mouf/security.rightsservice-splash' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\FileBasedRenderer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'vendor/mouf/security.rightsservice-splash/src/templates',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'rendererCacheService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'package',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 0,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      4 => 
      array (
        'value' => 'twigEnvironment',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'packageRenderer_mouf/security.simplelogincontroller' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\FileBasedRenderer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'vendor/mouf/security.simplelogincontroller/src/templates',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'rendererCacheService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'package',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 0,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      4 => 
      array (
        'value' => 'twigEnvironment',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'packageRenderer_mouf/security.user-management-ui' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\FileBasedRenderer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'vendor/mouf/security.user-management-ui/src/templates',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'rendererCacheService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'package',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 0,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      4 => 
      array (
        'value' => 'twigEnvironment',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'patch.default_type' => 
  array (
    'class' => 'Mouf\\Utils\\Patcher\\PatchType',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => '',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'Patches that should be always applied should have this type. Typically, use this type for DDL changes or reference data insertion.',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'patch.testdata_type' => 
  array (
    'class' => 'Mouf\\Utils\\Patcher\\PatchType',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'test_data',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'Use this type to mark patches that contain test data that should only be used in staging environment.',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'patchConnection' => 
  array (
    'class' => 'Mouf\\Database\\Patcher\\PatchConnection',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'patches',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'dbalConnection',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'patchService' => 
  array (
    'class' => 'Mouf\\Utils\\Patcher\\PatchService',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'patch.default_type',
          1 => 'patch.testdata_type',
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
          0 => 'patchConnection',
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setPatchs' => 
      array (
        0 => 'Mouf\\Security\\Migrations\\CreateUserRoleRightPatch',
      ),
    ),
  ),
  'psr.errorLogLogger' => 
  array (
    'class' => 'Mouf\\Utils\\Log\\Psr\\ErrorLogLogger',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'warning',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'readOnlyCheckBoxFormatter' => 
  array (
    'class' => 'Mouf\\Utils\\Common\\Formatters\\ReadOnlyCheckboxFormatter',
    'external' => false,
    'weak' => false,
  ),
  'rendererCacheService' => 
  array (
    'class' => 'Mouf\\Utils\\Cache\\InMemoryCache',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'chainWith' => 'apcCacheService',
    ),
  ),
  'replaceNullWithHyphen' => 
  array (
    'class' => 'Mouf\\Utils\\Common\\Formatters\\NullTransformationFormatter',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => '-',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'rightsService' => 
  array (
    'class' => 'Mouf\\Security\\RightsService\\MoufRightService',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'userService' => 'userService',
      'rightsDao' => 'Mouf\\Security\\DAO\\SecurityRightDao',
    ),
    'fieldProperties' => 
    array (
      'sessionPrefix' => 
      array (
        'value' => 'SECRET',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'roleDao' => 
  array (
    'class' => 'ShopFunnels\\Dao\\RoleDao',
    'external' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'tdbmService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'roleRightDao' => 
  array (
    'class' => 'ShopFunnels\\Dao\\RoleRightDao',
    'external' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'tdbmService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'rootController' => 
  array (
    'class' => 'ShopFunnels\\Controllers\\RootController',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'bootstrapTemplate',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'block.content',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'twigEnvironment',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'rootUrlInlineWebLibrary' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\InlineWebLibrary',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'rootUrlJsFile',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'rootUrlJsFile' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlFromFile',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'vendor/mouf/html.utils.weblibrarymanager/javascript/rootUrl.php',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'sessionManager' => 
  array (
    'class' => 'Mouf\\Utils\\Session\\SessionManager\\DefaultSessionManager',
    'external' => false,
  ),
  'shopFunnelsLibraryManager' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'src/Public/js/vendor.js',
          1 => 'src/Public/js/main.js',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
          0 => 'src/Public/css/vendor.css',
          1 => 'src/Public/css/main.css',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'simpleLoginController' => 
  array (
    'class' => 'Mouf\\Security\\Controllers\\SimpleLoginController',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'bootstrapTemplate',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'block.content',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'simpleLoginView',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 'userService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      4 => 
      array (
        'value' => 'return ROOT_URL;',
        'parametertype' => 'primitive',
        'type' => 'php',
        'metadata' => 
        array (
        ),
      ),
      5 => 
      array (
        'value' => 'login',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'simpleLoginView' => 
  array (
    'class' => 'Mouf\\Security\\Views\\SimpleLoginView',
    'external' => false,
    'weak' => false,
  ),
  'splashCachePool' => 
  array (
    'weak' => false,
    'comment' => '',
    'class' => 'Stash\\Pool',
    'external' => false,
    'code' => '$drivers = [
    new Stash\\Driver\\Ephemeral()
];

if (Stash\\Driver\\Apc::isAvailable()) {
    $drivers[] = new Stash\\Driver\\Apc([
        \'namespace\' => SECRET
    ]);
}

$drivers[] = new Stash\\Driver\\FileSystem([
    \'path\' => sys_get_temp_dir().\'/splash-\'.SECRET
]);

$compositeDriver = new Stash\\Driver\\Composite([\'drivers\'=>$drivers]);

return new Stash\\Pool($compositeDriver);',
  ),
  'swiftMailService' => 
  array (
    'class' => 'Mouf\\Utils\\Mailer\\SwiftMailService',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'swiftMailer',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'swiftMailTransport' => 
  array (
    'weak' => false,
    'comment' => '',
    'class' => 'Swift_SmtpTransport',
    'external' => false,
    'code' => '$transport = \\Swift_SmtpTransport::newInstance(MAIL_HOST, MAIL_PORT, MAIL_SSL);

if (MAIL_USERNAME) {
	$transport->setUsername(MAIL_USERNAME);
}
if (MAIL_PASSWORD) {
	$transport->setPassword(MAIL_PASSWORD);
}
if (MAIL_AUTH) {
    $transport->setAuthMode(MAIL_AUTH);
}

return $transport;',
  ),
  'swiftMailer' => 
  array (
    'weak' => false,
    'comment' => '',
    'class' => 'Swift_Mailer',
    'external' => false,
    'code' => 'return \\Swift_Mailer::newInstance($container->get(\'swiftMailTransport\'));',
  ),
  'tdbmConfiguration' => 
  array (
    'class' => 'Mouf\\Database\\TDBM\\MoufConfiguration',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'ShopFunnels\\Model',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'ShopFunnels\\Dao',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'dbalConnection',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 'namingStrategy',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      4 => 
      array (
        'value' => 'defaultDoctrineCache',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      5 => 
      array (
        'value' => NULL,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      6 => 
      array (
        'value' => NULL,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      7 => 
      array (
        'value' => 
        array (
          0 => 'Mouf\\Database\\TDBM\\Utils\\MoufDiListener',
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterProperties' => 
    array (
      'setDaoFactoryInstanceName' => 
      array (
        'value' => 'daoFactory',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'tdbmService' => 
  array (
    'class' => 'TheCodingMachine\\TDBM\\TDBMService',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'tdbmConfiguration',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'timestampToFrdateFormatter' => 
  array (
    'class' => 'Mouf\\Utils\\Common\\Formatters\\DateFormatter',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'timestamp',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'd/m/Y',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'twigCacheFileSystem' => 
  array (
    'class' => 'Twig_Cache_Filesystem',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => '// If we are running on a Unix environment, let\'s prepend the cache with the user id of the PHP process.
// This way, we can avoid rights conflicts.
if (function_exists(\'posix_geteuid\')) {
    $posixGetuid = posix_geteuid();
} else {
    $posixGetuid = \'\';
}
return rtrim(sys_get_temp_dir(), \'/\\\\\').\'/mouftwigtemplatemain_\'.$posixGetuid.str_replace(":", "", ROOT_PATH);',
        'parametertype' => 'primitive',
        'type' => 'php',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'twigDebugExtension' => 
  array (
    'class' => 'Twig_Extension_Debug',
    'external' => false,
    'weak' => false,
  ),
  'twigEnvironment' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\Twig\\MoufTwigEnvironment',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'twigLoaderFileSystem',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'return array(\'debug\' => DEBUG, \'auto_reload\' => true);',
        'parametertype' => 'primitive',
        'type' => 'php',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setCache' => 'twigCacheFileSystem',
      'setExtensions' => 
      array (
        0 => 'moufTwigExtension',
        1 => 'twigDebugExtension',
        2 => '__anonymous__bbb3_604724816',
      ),
    ),
  ),
  'twigLoaderFileSystem' => 
  array (
    'class' => 'Twig_Loader_Filesystem',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'return ROOT_PATH;',
        'parametertype' => 'primitive',
        'type' => 'php',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'userDao' => 
  array (
    'class' => 'ShopFunnels\\Dao\\UserDao',
    'external' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'tdbmService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'userMessageService' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\MessageService\\Service\\SessionMessageService',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'sessionManager' => 'sessionManager',
    ),
  ),
  'userService' => 
  array (
    'class' => 'Mouf\\Security\\UserService\\UserService',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'log' => 'psr.errorLogLogger',
      'sessionManager' => 'sessionManager',
      'authenticationListeners' => 
      array (
        0 => 'rightsService',
      ),
      'userDao' => 'Mouf\\Security\\DAO\\SecurityUserDao',
    ),
    'fieldProperties' => 
    array (
      'sessionPrefix' => 
      array (
        'value' => 'SECRET',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'whoopsMiddleware' => 
  array (
    'class' => 'Middlewares\\Whoops',
    'external' => false,
    'weak' => false,
  ),
));


unset($moufManager);

/**
 * This is the base class of the Manage Object User Friendly or Modular object user framework (MOUF) framework.
 * This object can be used to get the objects manage by MOUF.
 *
 */
class Mouf {
	public function getClosures() {
		return [
			'Mouf\\Mvc\\Splash\\Routers\\SplashDefaultRouter' => [
				'constructor' => [
					0 => function(ContainerInterface $container) {
						return $container;
					},
					7 => function(ContainerInterface $container) {
						return ROOT_URL;
					},
				],
			],
			'Mouf\\Mvc\\Splash\\Services\\ControllerAnalyzer' => [
				'constructor' => [
					0 => function(ContainerInterface $container) {
						return $container;
					},
				],
			],
			'__anonymous__bbb3_817177238' => [
				'constructor' => [
					0 => function(ContainerInterface $container) {
						return $container->get('whoopsMiddleware');
					},
				],
			],
			'__anonymous__bbb3_872310246' => [
				'constructor' => [
					0 => function(ContainerInterface $container) {
						return $container->get('Psr7Middlewares\\Middleware\\Payload');
					},
				],
			],
			'annotationReader' => function(ContainerInterface $container) {
				// Using composer autoloader
$loader = require ROOT_PATH . 'vendor/autoload.php';
\Doctrine\Common\Annotations\AnnotationRegistry::registerLoader(array($loader, 'loadClass'));

// Creating a new AnnotationReader
$reader = new \Doctrine\Common\Annotations\AnnotationReader();
return new \Doctrine\Common\Annotations\CachedReader($reader, $container->get("defaultDoctrineCache"));
			},
			'dbalConnection' => [
				'constructor' => [
					0 => function(ContainerInterface $container) {
						return array(
    "host" => DB_HOST,
    "user" => DB_USERNAME,
    "password" => DB_PASSWORD,
    "port" => DB_PORT,
    "dbname" => DB_NAME,
    "charset" => "utf8",
    "driverOptions" => array(
        1002 =>"SET NAMES utf8"
    )
);
					},
				],
			],
			'defaultDoctrineCache' => function(ContainerInterface $container) {
				// If DEBUG mode is on, let's just use an ArrayCache.
if (DEBUG) {
	$driver = new \Doctrine\Common\Cache\ArrayCache();
} else {
	// If APC is available, let's use APC
	if (extension_loaded("apcu")) {
		$driver = new \Doctrine\Common\Cache\ApcuCache();
	} else if (extension_loaded("apc")) {
		$driver = new \Doctrine\Common\Cache\ApcCache();
	} else {
		$driver = new \Doctrine\Common\Cache\PhpFileCache(sys_get_temp_dir().'/doctrinecache');
	}
}
$driver->setNamespace(SECRET);
return $driver;

			},
			'moufTwigExtension' => [
				'constructor' => [
					0 => function(ContainerInterface $container) {
						return $container;
					},
				],
			],
			'simpleLoginController' => [
				'constructor' => [
					4 => function(ContainerInterface $container) {
						return ROOT_URL;
					},
				],
			],
			'splashCachePool' => function(ContainerInterface $container) {
				$drivers = [
    new Stash\Driver\Ephemeral()
];

if (Stash\Driver\Apc::isAvailable()) {
    $drivers[] = new Stash\Driver\Apc([
        'namespace' => SECRET
    ]);
}

$drivers[] = new Stash\Driver\FileSystem([
    'path' => sys_get_temp_dir().'/splash-'.SECRET
]);

$compositeDriver = new Stash\Driver\Composite(['drivers'=>$drivers]);

return new Stash\Pool($compositeDriver);
			},
			'swiftMailTransport' => function(ContainerInterface $container) {
				$transport = \Swift_SmtpTransport::newInstance(MAIL_HOST, MAIL_PORT, MAIL_SSL);

if (MAIL_USERNAME) {
	$transport->setUsername(MAIL_USERNAME);
}
if (MAIL_PASSWORD) {
	$transport->setPassword(MAIL_PASSWORD);
}
if (MAIL_AUTH) {
    $transport->setAuthMode(MAIL_AUTH);
}

return $transport;
			},
			'swiftMailer' => function(ContainerInterface $container) {
				return \Swift_Mailer::newInstance($container->get('swiftMailTransport'));
			},
			'twigCacheFileSystem' => [
				'constructor' => [
					0 => function(ContainerInterface $container) {
						// If we are running on a Unix environment, let's prepend the cache with the user id of the PHP process.
// This way, we can avoid rights conflicts.
if (function_exists('posix_geteuid')) {
    $posixGetuid = posix_geteuid();
} else {
    $posixGetuid = '';
}
return rtrim(sys_get_temp_dir(), '/\\').'/mouftwigtemplatemain_'.$posixGetuid.str_replace(":", "", ROOT_PATH);
					},
				],
			],
			'twigEnvironment' => [
				'constructor' => [
					1 => function(ContainerInterface $container) {
						return array('debug' => DEBUG, 'auto_reload' => true);
					},
				],
			],
			'twigLoaderFileSystem' => [
				'constructor' => [
					0 => function(ContainerInterface $container) {
						return ROOT_PATH;
					},
				],
			],
		];
	}
	/**
	 * @return Mouf\Database\TDBM\Utils\MoufDiListener
	 */
	 public static function getMoufDatabaseTDBMUtilsMoufDiListener() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Database\\TDBM\\Utils\\MoufDiListener');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Controllers\HttpErrorsController
	 */
	 public static function getMoufMvcSplashControllersHttpErrorsController() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Mvc\\Splash\\Controllers\\HttpErrorsController');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Routers\ExceptionRouter
	 */
	 public static function getMoufMvcSplashRoutersExceptionRouter() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Mvc\\Splash\\Routers\\ExceptionRouter');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Routers\NotFoundRouter
	 */
	 public static function getMoufMvcSplashRoutersNotFoundRouter() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Mvc\\Splash\\Routers\\NotFoundRouter');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Routers\PhpVarsCheckRouter
	 */
	 public static function getMoufMvcSplashRoutersPhpVarsCheckRouter() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Mvc\\Splash\\Routers\\PhpVarsCheckRouter');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Routers\SplashDefaultRouter
	 */
	 public static function getMoufMvcSplashRoutersSplashDefaultRouter() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Mvc\\Splash\\Routers\\SplashDefaultRouter');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Services\ControllerAnalyzer
	 */
	 public static function getMoufMvcSplashServicesControllerAnalyzer() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Mvc\\Splash\\Services\\ControllerAnalyzer');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Services\ControllerRegistry
	 */
	 public static function getMoufMvcSplashServicesControllerRegistry() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Mvc\\Splash\\Services\\ControllerRegistry');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Services\MoufControllerExplorer
	 */
	 public static function getMoufMvcSplashServicesMoufControllerExplorer() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Mvc\\Splash\\Services\\MoufControllerExplorer');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Services\MoufExplorerUrlProvider
	 */
	 public static function getMoufMvcSplashServicesMoufExplorerUrlProvider() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Mvc\\Splash\\Services\\MoufExplorerUrlProvider');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Services\ParameterFetcherRegistry
	 */
	 public static function getMoufMvcSplashServicesParameterFetcherRegistry() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Mvc\\Splash\\Services\\ParameterFetcherRegistry');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Services\SplashRequestFetcher
	 */
	 public static function getMoufMvcSplashServicesSplashRequestFetcher() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Mvc\\Splash\\Services\\SplashRequestFetcher');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Services\SplashRequestParameterFetcher
	 */
	 public static function getMoufMvcSplashServicesSplashRequestParameterFetcher() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Mvc\\Splash\\Services\\SplashRequestParameterFetcher');
	 }

	/**
	 * @return Mouf\Mvc\Splash\SplashMiddleware
	 */
	 public static function getMoufMvcSplashSplashMiddleware() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Mvc\\Splash\\SplashMiddleware');
	 }

	/**
	 * @return Mouf\Security\DAO\SecurityRightDao
	 */
	 public static function getMoufSecurityDAOSecurityRightDao() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Security\\DAO\\SecurityRightDao');
	 }

	/**
	 * @return Mouf\Security\DAO\SecurityUserDao
	 */
	 public static function getMoufSecurityDAOSecurityUserDao() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Security\\DAO\\SecurityUserDao');
	 }

	/**
	 * @return Mouf\Security\ForbiddenMiddleware
	 */
	 public static function getMoufSecurityForbiddenMiddleware() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Security\\ForbiddenMiddleware');
	 }

	/**
	 * @return Mouf\Security\Migrations\CreateUserRoleRightPatch
	 */
	 public static function getMoufSecurityMigrationsCreateUserRoleRightPatch() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Security\\Migrations\\CreateUserRoleRightPatch');
	 }

	/**
	 * @return Mouf\Security\Password\ForgotYourPasswordController
	 */
	 public static function getMoufSecurityPasswordForgotYourPasswordController() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Security\\Password\\ForgotYourPasswordController');
	 }

	/**
	 * @return Mouf\Security\Password\ForgotYourPasswordService
	 */
	 public static function getMoufSecurityPasswordForgotYourPasswordService() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Security\\Password\\ForgotYourPasswordService');
	 }

	/**
	 * @return Mouf\Security\Password\PasswordStrengthCheck
	 */
	 public static function getMoufSecurityPasswordPasswordStrengthCheck() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Security\\Password\\PasswordStrengthCheck');
	 }

	/**
	 * @return Mouf\Security\Rights\RightsRegistry
	 */
	 public static function getMoufSecurityRightsRightsRegistry() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Security\\Rights\\RightsRegistry');
	 }

	/**
	 * @return Mouf\Security\UnauthorizedMiddleware
	 */
	 public static function getMoufSecurityUnauthorizedMiddleware() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Security\\UnauthorizedMiddleware');
	 }

	/**
	 * @return Psr7Middlewares\Middleware\Payload
	 */
	 public static function getPsr7MiddlewaresMiddlewarePayload() {
	 	return MoufManager::getMoufManager()->get('Psr7Middlewares\\Middleware\\Payload');
	 }

	/**
	 * @return Doctrine\Common\Annotations\CachedReader
	 */
	 public static function getAnnotationReader() {
	 	return MoufManager::getMoufManager()->get('annotationReader');
	 }

	/**
	 * @return Mouf\Utils\Cache\ApcCache
	 */
	 public static function getApcCacheService() {
	 	return MoufManager::getMoufManager()->get('apcCacheService');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_content() {
	 	return MoufManager::getMoufManager()->get('block.content');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_footer() {
	 	return MoufManager::getMoufManager()->get('block.footer');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_header() {
	 	return MoufManager::getMoufManager()->get('block.header');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_left() {
	 	return MoufManager::getMoufManager()->get('block.left');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_right() {
	 	return MoufManager::getMoufManager()->get('block.right');
	 }

	/**
	 * @return Mouf\Utils\Common\Formatters\PrefixSuffixFormatter
	 */
	 public static function getBoldFormatter() {
	 	return MoufManager::getMoufManager()->get('boldFormatter');
	 }

	/**
	 * @return Mouf\Html\Renderer\FileBasedRenderer
	 */
	 public static function getBootstrapRenderer() {
	 	return MoufManager::getMoufManager()->get('bootstrapRenderer');
	 }

	/**
	 * @return Mouf\Html\Template\BootstrapTemplate
	 */
	 public static function getBootstrapTemplate() {
	 	return MoufManager::getMoufManager()->get('bootstrapTemplate');
	 }

	/**
	 * @return Mouf\Utils\I18n\Fine\Language\CascadingLanguageDetection
	 */
	 public static function getCascadingLanguageDetection() {
	 	return MoufManager::getMoufManager()->get('cascadingLanguageDetection');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getComponent_bootstrap() {
	 	return MoufManager::getMoufManager()->get('component.bootstrap');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getComponent_jquery() {
	 	return MoufManager::getMoufManager()->get('component.jquery');
	 }

	/**
	 * @return Mouf\Console\ConsoleApplication
	 */
	 public static function getConsole() {
	 	return MoufManager::getMoufManager()->get('console');
	 }

	/**
	 * @return Mouf\Html\Renderer\FileBasedRenderer
	 */
	 public static function getCustomRenderer() {
	 	return MoufManager::getMoufManager()->get('customRenderer');
	 }

	/**
	 * @return ShopFunnels\Dao\Generated\DaoFactory
	 */
	 public static function getDaoFactory() {
	 	return MoufManager::getMoufManager()->get('daoFactory');
	 }

	/**
	 * @return Doctrine\DBAL\Connection
	 */
	 public static function getDbalConnection() {
	 	return MoufManager::getMoufManager()->get('dbalConnection');
	 }

	/**
	 * @return Doctrine\DBAL\Tools\Console\Helper\ConnectionHelper
	 */
	 public static function getDbalConnectionHelper() {
	 	return MoufManager::getMoufManager()->get('dbalConnectionHelper');
	 }

	/**
	 * @return Doctrine\DBAL\Tools\Console\Command\ImportCommand
	 */
	 public static function getDbalImportCommand() {
	 	return MoufManager::getMoufManager()->get('dbalImportCommand');
	 }

	/**
	 * @return Doctrine\DBAL\Tools\Console\Command\ReservedWordsCommand
	 */
	 public static function getDbalReservedWordsCommand() {
	 	return MoufManager::getMoufManager()->get('dbalReservedWordsCommand');
	 }

	/**
	 * @return Doctrine\DBAL\Tools\Console\Command\RunSqlCommand
	 */
	 public static function getDbalRunSqlCommand() {
	 	return MoufManager::getMoufManager()->get('dbalRunSqlCommand');
	 }

	/**
	 * @return Doctrine\Common\Cache\ArrayCache
	 */
	 public static function getDefaultDoctrineCache() {
	 	return MoufManager::getMoufManager()->get('defaultDoctrineCache');
	 }

	/**
	 * @return Mouf\Html\Renderer\AutoChainRenderer
	 */
	 public static function getDefaultRenderer() {
	 	return MoufManager::getMoufManager()->get('defaultRenderer');
	 }

	/**
	 * @return Mouf\Utils\I18n\Fine\Common\FineCascadingTranslator
	 */
	 public static function getDefaultTranslationService() {
	 	return MoufManager::getMoufManager()->get('defaultTranslationService');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibraryManager
	 */
	 public static function getDefaultWebLibraryManager() {
	 	return MoufManager::getMoufManager()->get('defaultWebLibraryManager');
	 }

	/**
	 * @return Doctrine\DBAL\Configuration
	 */
	 public static function getDoctrineDbalConfiguration() {
	 	return MoufManager::getMoufManager()->get('doctrineDbalConfiguration');
	 }

	/**
	 * @return Mouf\Utils\Common\Doctrine\Cache\DoctrineCacheAdapter
	 */
	 public static function getDoctrineMoufCache() {
	 	return MoufManager::getMoufManager()->get('doctrineMoufCache');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getEvolugridLibrary() {
	 	return MoufManager::getMoufManager()->get('evolugridLibrary');
	 }

	/**
	 * @return Mouf\Utils\Cache\FileCache
	 */
	 public static function getFileCacheService() {
	 	return MoufManager::getMoufManager()->get('fileCacheService');
	 }

	/**
	 * @return Mouf\Utils\I18n\Fine\Translator\FileTranslator
	 */
	 public static function getFileTranslatorService() {
	 	return MoufManager::getMoufManager()->get('fileTranslatorService');
	 }

	/**
	 * @return Mouf\Utils\I18n\Fine\Language\FixedLanguageDetection
	 */
	 public static function getFixedEnglishLanguageDetection() {
	 	return MoufManager::getMoufManager()->get('fixedEnglishLanguageDetection');
	 }

	/**
	 * @return TheCodingMachine\Mail\Template\SwiftTwigMailTemplate
	 */
	 public static function getForgotYourPasswordMailTemplate() {
	 	return MoufManager::getMoufManager()->get('forgotYourPasswordMailTemplate');
	 }

	/**
	 * @return Mouf\Utils\I18n\Fine\Translator\FileTranslator
	 */
	 public static function getForgotYourPasswordTranslator() {
	 	return MoufManager::getMoufManager()->get('forgotYourPasswordTranslator');
	 }

	/**
	 * @return TheCodingMachine\TDBM\Commands\GenerateCommand
	 */
	 public static function getGenerateCommand() {
	 	return MoufManager::getMoufManager()->get('generateCommand');
	 }

	/**
	 * @return Mouf\Console\HelperSet
	 */
	 public static function getHelperSet() {
	 	return MoufManager::getMoufManager()->get('helperSet');
	 }

	/**
	 * @return Mouf\Utils\Common\Formatters\PrefixSuffixFormatter
	 */
	 public static function getItalicFormatter() {
	 	return MoufManager::getMoufManager()->get('italicFormatter');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getJQueryHistory() {
	 	return MoufManager::getMoufManager()->get('jQueryHistory');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getJQueryLibrary() {
	 	return MoufManager::getMoufManager()->get('jQueryLibrary');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getMessageServiceLibrary() {
	 	return MoufManager::getMoufManager()->get('messageServiceLibrary');
	 }

	/**
	 * @return Mouf\Html\Widgets\MessageService\Widget\MessageWidget
	 */
	 public static function getMessageWidget() {
	 	return MoufManager::getMoufManager()->get('messageWidget');
	 }

	/**
	 * @return Mouf\Html\Renderer\Twig\MoufTwigExtension
	 */
	 public static function getMoufTwigExtension() {
	 	return MoufManager::getMoufManager()->get('moufTwigExtension');
	 }

	/**
	 * @return TheCodingMachine\TDBM\Utils\DefaultNamingStrategy
	 */
	 public static function getNamingStrategy() {
	 	return MoufManager::getMoufManager()->get('namingStrategy');
	 }

	/**
	 * @return Mouf\Html\Renderer\FileBasedRenderer
	 */
	 public static function getPackageRenderer_moufhtml_utils_weblibrarymanager() {
	 	return MoufManager::getMoufManager()->get('packageRenderer_mouf/html.utils.weblibrarymanager');
	 }

	/**
	 * @return Mouf\Html\Renderer\FileBasedRenderer
	 */
	 public static function getPackageRenderer_moufhtml_widgets_menu() {
	 	return MoufManager::getMoufManager()->get('packageRenderer_mouf/html.widgets.menu');
	 }

	/**
	 * @return Mouf\Html\Renderer\FileBasedRenderer
	 */
	 public static function getPackageRenderer_moufhtml_widgets_messageservice() {
	 	return MoufManager::getMoufManager()->get('packageRenderer_mouf/html.widgets.messageservice');
	 }

	/**
	 * @return Mouf\Html\Renderer\FileBasedRenderer
	 */
	 public static function getPackageRenderer_moufsecurity_forgotyourpassword() {
	 	return MoufManager::getMoufManager()->get('packageRenderer_mouf/security.forgot-your-password');
	 }

	/**
	 * @return Mouf\Html\Renderer\FileBasedRenderer
	 */
	 public static function getPackageRenderer_moufsecurity_rightsservicesplash() {
	 	return MoufManager::getMoufManager()->get('packageRenderer_mouf/security.rightsservice-splash');
	 }

	/**
	 * @return Mouf\Html\Renderer\FileBasedRenderer
	 */
	 public static function getPackageRenderer_moufsecurity_simplelogincontroller() {
	 	return MoufManager::getMoufManager()->get('packageRenderer_mouf/security.simplelogincontroller');
	 }

	/**
	 * @return Mouf\Html\Renderer\FileBasedRenderer
	 */
	 public static function getPackageRenderer_moufsecurity_usermanagementui() {
	 	return MoufManager::getMoufManager()->get('packageRenderer_mouf/security.user-management-ui');
	 }

	/**
	 * @return Mouf\Utils\Patcher\PatchType
	 */
	 public static function getPatch_default_type() {
	 	return MoufManager::getMoufManager()->get('patch.default_type');
	 }

	/**
	 * @return Mouf\Utils\Patcher\PatchType
	 */
	 public static function getPatch_testdata_type() {
	 	return MoufManager::getMoufManager()->get('patch.testdata_type');
	 }

	/**
	 * @return Mouf\Database\Patcher\PatchConnection
	 */
	 public static function getPatchConnection() {
	 	return MoufManager::getMoufManager()->get('patchConnection');
	 }

	/**
	 * @return Mouf\Utils\Patcher\PatchService
	 */
	 public static function getPatchService() {
	 	return MoufManager::getMoufManager()->get('patchService');
	 }

	/**
	 * @return Mouf\Utils\Log\Psr\ErrorLogLogger
	 */
	 public static function getPsr_errorLogLogger() {
	 	return MoufManager::getMoufManager()->get('psr.errorLogLogger');
	 }

	/**
	 * @return Mouf\Utils\Common\Formatters\ReadOnlyCheckboxFormatter
	 */
	 public static function getReadOnlyCheckBoxFormatter() {
	 	return MoufManager::getMoufManager()->get('readOnlyCheckBoxFormatter');
	 }

	/**
	 * @return Mouf\Utils\Cache\InMemoryCache
	 */
	 public static function getRendererCacheService() {
	 	return MoufManager::getMoufManager()->get('rendererCacheService');
	 }

	/**
	 * @return Mouf\Utils\Common\Formatters\NullTransformationFormatter
	 */
	 public static function getReplaceNullWithHyphen() {
	 	return MoufManager::getMoufManager()->get('replaceNullWithHyphen');
	 }

	/**
	 * @return Mouf\Security\RightsService\MoufRightService
	 */
	 public static function getRightsService() {
	 	return MoufManager::getMoufManager()->get('rightsService');
	 }

	/**
	 * @return ShopFunnels\Dao\RoleDao
	 */
	 public static function getRoleDao() {
	 	return MoufManager::getMoufManager()->get('roleDao');
	 }

	/**
	 * @return ShopFunnels\Dao\RoleRightDao
	 */
	 public static function getRoleRightDao() {
	 	return MoufManager::getMoufManager()->get('roleRightDao');
	 }

	/**
	 * @return ShopFunnels\Controllers\RootController
	 */
	 public static function getRootController() {
	 	return MoufManager::getMoufManager()->get('rootController');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\InlineWebLibrary
	 */
	 public static function getRootUrlInlineWebLibrary() {
	 	return MoufManager::getMoufManager()->get('rootUrlInlineWebLibrary');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlFromFile
	 */
	 public static function getRootUrlJsFile() {
	 	return MoufManager::getMoufManager()->get('rootUrlJsFile');
	 }

	/**
	 * @return Mouf\Utils\Session\SessionManager\DefaultSessionManager
	 */
	 public static function getSessionManager() {
	 	return MoufManager::getMoufManager()->get('sessionManager');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getShopFunnelsLibraryManager() {
	 	return MoufManager::getMoufManager()->get('shopFunnelsLibraryManager');
	 }

	/**
	 * @return Mouf\Security\Controllers\SimpleLoginController
	 */
	 public static function getSimpleLoginController() {
	 	return MoufManager::getMoufManager()->get('simpleLoginController');
	 }

	/**
	 * @return Mouf\Security\Views\SimpleLoginView
	 */
	 public static function getSimpleLoginView() {
	 	return MoufManager::getMoufManager()->get('simpleLoginView');
	 }

	/**
	 * @return Stash\Pool
	 */
	 public static function getSplashCachePool() {
	 	return MoufManager::getMoufManager()->get('splashCachePool');
	 }

	/**
	 * @return Mouf\Utils\Mailer\SwiftMailService
	 */
	 public static function getSwiftMailService() {
	 	return MoufManager::getMoufManager()->get('swiftMailService');
	 }

	/**
	 * @return Swift_SmtpTransport
	 */
	 public static function getSwiftMailTransport() {
	 	return MoufManager::getMoufManager()->get('swiftMailTransport');
	 }

	/**
	 * @return Swift_Mailer
	 */
	 public static function getSwiftMailer() {
	 	return MoufManager::getMoufManager()->get('swiftMailer');
	 }

	/**
	 * @return Mouf\Database\TDBM\MoufConfiguration
	 */
	 public static function getTdbmConfiguration() {
	 	return MoufManager::getMoufManager()->get('tdbmConfiguration');
	 }

	/**
	 * @return TheCodingMachine\TDBM\TDBMService
	 */
	 public static function getTdbmService() {
	 	return MoufManager::getMoufManager()->get('tdbmService');
	 }

	/**
	 * @return Mouf\Utils\Common\Formatters\DateFormatter
	 */
	 public static function getTimestampToFrdateFormatter() {
	 	return MoufManager::getMoufManager()->get('timestampToFrdateFormatter');
	 }

	/**
	 * @return Twig_Cache_Filesystem
	 */
	 public static function getTwigCacheFileSystem() {
	 	return MoufManager::getMoufManager()->get('twigCacheFileSystem');
	 }

	/**
	 * @return Twig_Extension_Debug
	 */
	 public static function getTwigDebugExtension() {
	 	return MoufManager::getMoufManager()->get('twigDebugExtension');
	 }

	/**
	 * @return Mouf\Html\Renderer\Twig\MoufTwigEnvironment
	 */
	 public static function getTwigEnvironment() {
	 	return MoufManager::getMoufManager()->get('twigEnvironment');
	 }

	/**
	 * @return Twig_Loader_Filesystem
	 */
	 public static function getTwigLoaderFileSystem() {
	 	return MoufManager::getMoufManager()->get('twigLoaderFileSystem');
	 }

	/**
	 * @return ShopFunnels\Dao\UserDao
	 */
	 public static function getUserDao() {
	 	return MoufManager::getMoufManager()->get('userDao');
	 }

	/**
	 * @return Mouf\Html\Widgets\MessageService\Service\SessionMessageService
	 */
	 public static function getUserMessageService() {
	 	return MoufManager::getMoufManager()->get('userMessageService');
	 }

	/**
	 * @return Mouf\Security\UserService\UserService
	 */
	 public static function getUserService() {
	 	return MoufManager::getMoufManager()->get('userService');
	 }

	/**
	 * @return Middlewares\Whoops
	 */
	 public static function getWhoopsMiddleware() {
	 	return MoufManager::getMoufManager()->get('whoopsMiddleware');
	 }

}
