<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace ShopFunnels\Dao;

use ShopFunnels\Dao\Generated\AbstractFunnelFormDao;

/**
 * The FunnelFormDao class will maintain the persistence of FunnelForm class into the funnel_forms table.
 */
class FunnelFormDao extends AbstractFunnelFormDao
{
}
