<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace ShopFunnels\Dao;

use ShopFunnels\Dao\Generated\AbstractFunnelFormTypeDao;

/**
 * The FunnelFormTypeDao class will maintain the persistence of FunnelFormType class into the funnel_form_types table.
 */
class FunnelFormTypeDao extends AbstractFunnelFormTypeDao
{
}
