<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace ShopFunnels\Dao;

use ShopFunnels\Dao\Generated\AbstractProductDao;

/**
 * The ProductDao class will maintain the persistence of Product class into the products table.
 */
class ProductDao extends AbstractProductDao
{
}
