<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace ShopFunnels\Dao;

use ShopFunnels\Dao\Generated\AbstractProductTypeDao;

/**
 * The ProductTypeDao class will maintain the persistence of ProductType class into the product_types table.
 */
class ProductTypeDao extends AbstractProductTypeDao
{
}
