<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace ShopFunnels\Dao;

use ShopFunnels\Dao\Generated\AbstractRoleDao;

/**
 * The RoleDao class will maintain the persistence of Role class into the roles table.
 */
class RoleDao extends AbstractRoleDao
{
}
