<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace ShopFunnels\Dao;

use ShopFunnels\Dao\Generated\AbstractStoreDao;

/**
 * The StoreDao class will maintain the persistence of Store class into the stores table.
 */
class StoreDao extends AbstractStoreDao
{
    /**
     * Get valid stores by name.
     *
     * @param string $storeName
     * @return mixed
     */
    public function getValidStoresByName(string $storeName)
    {
        return $this->find('name = :name AND valid = 1', ['name' => $storeName], null);
    }
}
