<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace ShopFunnels\Dao;

use ShopFunnels\Dao\Generated\AbstractVariantStyleDao;

/**
 * The VariantStyleDao class will maintain the persistence of VariantStyle class into the variant_styles table.
 */
class VariantStyleDao extends AbstractVariantStyleDao
{
}
