<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace ShopFunnels\Dao;

use ShopFunnels\Dao\Generated\AbstractVariantTypeDao;

/**
 * The VariantTypeDao class will maintain the persistence of VariantType class into the variant_types table.
 */
class VariantTypeDao extends AbstractVariantTypeDao
{
}
