<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace ShopFunnels\Model;

use ShopFunnels\Model\Generated\AbstractFunnelForm;

/**
 * The FunnelForm class maps the 'funnel_forms' table in database.
 */
class FunnelForm extends AbstractFunnelForm
{
}
