<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace ShopFunnels\Model;

use ShopFunnels\Model\Generated\AbstractFunnelFormType;

/**
 * The FunnelFormType class maps the 'funnel_form_types' table in database.
 */
class FunnelFormType extends AbstractFunnelFormType
{
}
