<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace ShopFunnels\Model;

use ShopFunnels\Model\Generated\AbstractProduct;

/**
 * The Product class maps the 'products' table in database.
 */
class Product extends AbstractProduct
{
}
