<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace ShopFunnels\Model;

use ShopFunnels\Model\Generated\AbstractProductType;

/**
 * The ProductType class maps the 'product_types' table in database.
 */
class ProductType extends AbstractProductType
{
}
