<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace ShopFunnels\Model;

use ShopFunnels\Model\Generated\AbstractRoleRight;

/**
 * The RoleRight class maps the 'roles_rights' table in database.
 */
class RoleRight extends AbstractRoleRight
{
}
