<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace ShopFunnels\Model;

use ShopFunnels\Model\Generated\AbstractStore;

/**
 * The Store class maps the 'stores' table in database.
 */
class Store extends AbstractStore
{
}
