<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace ShopFunnels\Model;

use ShopFunnels\Model\Generated\AbstractUser;

/**
 * The User class maps the 'users' table in database.
 */
class User extends AbstractUser
{
}
