<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace ShopFunnels\Model;

use ShopFunnels\Model\Generated\AbstractVariantType;

/**
 * The VariantType class maps the 'variant_types' table in database.
 */
class VariantType extends AbstractVariantType
{
}
